---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/pages/index.md
  label: Contenu
- type: heading
  label: Fruits
- type: directory
  path: src/pages/fruits
  label: Fruits
  create: all
  match: "**/*"
  templates:
  - fruit
- type: heading
  label: Offres
- type: directory
  path: src/pages/offers/station
  label: Station
  create: all
  match: "**/*"
  templates:
  - offers-champs
- type: directory
  path: src/pages/offers/verger
  label: Verger
  create: documents
  match: "**/*"
  templates:
  - offer-admin
upload_dir: src/images
public_path: src/images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
  publish_command: gatsby build
  output_directory: public
  preview_command: gatsby build
