---
label: Site
hide_body: true
display_field: title
fields:
- type: text
  name: template
  label: Template
  hidden: true
  description: Page Template
  default: home
- type: text
  name: title
  label: Titre
- name: image
  type: file
  config:
    maxSize: 250
  label: Visuel
- type: field_group
  name: about
  label: À propos
  fields:
  - type: text
    name: title
    label: Titre
  - name: text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Texte
  - name: image
    type: file
    config:
      maxSize: 250
    label: Visuel
- type: field_group
  name: verger
  label: Le Verger
  fields:
  - name: eco_responsable
    type: text
    config:
      required: false
    label: Eco-responsable
  - type: field_group_list
    name: content
    label: content
    fields:
    - type: text
      name: title
      label: Titre
    - type: textarea
      name: text
      label: Texte
      config:
        wysiwyg: true
        schema:
          format: html-blocks
    config:
      labelField: title
      max: '2'
  - name: image
    type: file
    config:
      maxSize: 250
    label: Visuel
- type: field_group
  name: fruits
  label: Fruits
  fields:
  - type: text
    name: subtitle
    label: Sous-titre
  - type: text
    name: title
    label: Titre
- type: field_group
  name: bref
  label: En bref
  fields:
  - type: text
    name: title
    label: Title
  - name: text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Texte
- type: field_group
  name: recrutment
  label: Recrutement
  fields:
  - type: text
    name: title
    label: Titre
  - type: textarea
    name: text
    label: Texte
    config:
      wysiwyg: true
      schema:
        format: html-blocks
  - name: image
    type: file
    config:
      maxSize: 250
    label: Visuel
- type: field_group
  name: apply
  label: Postuler
  fields:
  - type: text
    name: title
    label: Titre
  - type: textarea
    name: text
    label: Texte
    config:
      wysiwyg: true
      schema:
        format: html-blocks
  - name: file
    type: file
    config:
      maxSize: 250
    label: Fichier
    description: Dépôt de dossier
  - type: text
    name: phone
    label: Téléphone
  - type: text
    name: email
    label: Email
- name: hve
  type: field_group
  config: {}
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Titre
  - name: text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Texte
  label: HVE
pages:
- src/pages/index.md
