---
label: Site
hide_body: true
display_field: title
fields:
- type: text
  name: template
  label: Template
  hidden: true
  description: Page Template
  default: home
- type: text
  name: title
  label: Titre
- name: image
  type: file
  config:
    maxSize: 250
  label: Visuel
- type: field_group
  name: about
  label: À propos
  fields:
  - type: text
    name: title
    label: Titre
  - name: text_col_1
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Texte
    description: Texte Colonne gauche
  - name: text_col_2
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Texte
    description: Texte Colonne droite
  - name: image
    type: file
    config:
      maxSize: 250
    label: Visuel
- type: field_group
  name: verger
  label: Le Verger
  fields:
  - name: text_col_1
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Texte Colonne droite
  - name: text_col_2
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Texte Colonne gauche
  - name: eco_responsable
    type: text
    config:
      required: false
    label: Eco-responsable
  - name: image
    type: file
    config:
      maxSize: 250
    label: Visuel
- type: field_group
  name: fruits
  label: Fruits
  fields:
  - name: title
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Titre
  - name: fruits
    type: list
    config:
      use_select: true
      min: 
      max: 
      source:
        type: pages
        section: fruits
    label: Fruits
    description: Ordre d'affichage des fruits
- type: field_group
  name: bref
  label: En bref
  fields:
  - name: title
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Titre
  - name: text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Texte
- type: field_group
  name: recrutment
  label: Recrutement
  fields:
  - type: text
    name: title
    label: Titre
  - type: textarea
    name: text
    label: Texte
    config:
      wysiwyg: true
      schema:
        format: html-blocks
  - name: image
    type: file
    config:
      maxSize: 250
    label: Visuel
- type: field_group
  name: apply
  label: Postuler
  fields:
  - type: textarea
    name: text
    label: Texte
    config:
      wysiwyg: true
      schema:
        format: html-blocks
  - name: file
    type: file
    config:
      maxSize: 250
    label: Fichier
    description: Dépôt de dossier
  - type: text
    name: phone
    label: Téléphone
  - type: text
    name: email
    label: Email
- name: hve
  type: field_group
  config: {}
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Titre
  - name: text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Texte
  label: HVE
pages:
- src/pages/index.md
